<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\Mood;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $focusMood = Mood::where('name', 'Focus')->first();
        $relaxingMood = Mood::where('name', 'Relaxing')->first();
        $energyMood = Mood::where('name', 'Energy')->first();

        $coffeeCat = Category::where('slug', 'coffee')->first();
        $brownieCat = Category::where('slug', 'brownies')->first();
        $dealCat = Category::where('slug', 'deals')->first();

        Product::insert([
            // === ENERGY MOOD (Bright, vibrant, highly caffeinated) ===
            [
                'name' => 'Classic Americano',
                'price' => 12.00,
                'mood_id' => $energyMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'A bold, crisp, and high-caffeine wake-up call to jumpstart your morning.',
                'image' => '/images/coffee/Americano.jpg',
                'farmer_name' => 'Mateo Silva',
                'country_origin' => 'Colombia',
                'altitude' => '1,750m',
                'farm_story' => 'Grown in the high-altitude volcanic soils of Huila, Colombia. Mateo hand-washes these beans in natural spring water, resulting in a clean, bright, and highly energetic cup.',
                'reward_points' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bright Fruity Pour-Over',
                'price' => 15.50,
                'mood_id' => $energyMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Vibrant berry notes with a sparkling acidity that refreshes the mind and boosts energy.',
                'image' => '/images/coffee/Fruity  Coffee.jpg',
                'farmer_name' => 'Amina Diallo',
                'country_origin' => 'Ethiopia',
                'altitude' => '2,100m',
                'farm_story' => 'Sun-dried on raised beds in Yirgacheffe, Amina\'s harvest preserves the delicate natural sugars of the coffee cherry, creating an incredibly vibrant and fruity profile.',
                'reward_points' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intense Ristretto',
                'price' => 14.00,
                'mood_id' => $energyMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'A short, highly concentrated shot of pure energy and intense flavor.',
                'image' => '/images/coffee/Ristretto.jpg',
                'farmer_name' => 'Luca Rossi',
                'country_origin' => 'Italy (Roasted) / Brazil (Grown)',
                'altitude' => '1,100m',
                'farm_story' => 'A traditional Italian roast crafted from dense Brazilian beans. Roasted slow and dark to maximize the syrup-like texture and explosive energy.',
                'reward_points' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === FOCUS MOOD (Earthy, grounded, nutty, low acidity) ===
            [
                'name' => 'Toasted Hazelnut Blend',
                'price' => 16.00,
                'mood_id' => $focusMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Earthy and grounding nutty flavors that calm a racing mind and enhance deep focus.',
                'image' => '/images/coffee/Hazelnut coffee.jpg',
                'farmer_name' => 'Isabella Santos',
                'country_origin' => 'Brazil',
                'altitude' => '1,200m',
                'farm_story' => 'Isabella focuses on sustainable, shade-grown methods in Minas Gerais. These naturally sweet beans have heavy nutty undertones perfect for anchoring your thoughts.',
                'reward_points' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chocolatey Nutty Brew',
                'price' => 17.50,
                'mood_id' => $focusMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'A dark, rich brew combining cocoa and roasted nuts for a steady, distraction-free workflow.',
                'image' => '/images/coffee/Chocolatey Nutty Coffee.jpg',
                'farmer_name' => 'Carlos Mendez',
                'country_origin' => 'Guatemala',
                'altitude' => '1,550m',
                'farm_story' => 'Grown under the shade of Macadamia trees in Antigua. Carlos allows the beans to naturally absorb the surrounding nutty and cocoa characteristics of the rich soil.',
                'reward_points' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pure Espresso',
                'price' => 11.00,
                'mood_id' => $focusMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Unadulterated, sharp, and intense. Forces you to sip slowly and lock into your task.',
                'image' => '/images/coffee/Espresso.jpg',
                'farmer_name' => 'Kiptoo Farm',
                'country_origin' => 'Kenya',
                'altitude' => '1,800m',
                'farm_story' => 'These strictly hard beans are precision-sorted by the Kiptoo family. When extracted as espresso, they yield a thick crema and laser-focused clarity.',
                'reward_points' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === RELAXING MOOD (Sweet, comforting, warm, spiced) ===
            [
                'name' => 'Warm Caramel Latte',
                'price' => 18.00,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Smooth, creamy textures and gooey caramel soothe the nervous system on a lazy Sunday.',
                'image' => '/images/coffee/caramel coffee.jpg',
                'farmer_name' => 'Juan Perez',
                'country_origin' => 'Honduras',
                'altitude' => '1,300m',
                'farm_story' => 'Juan’s coffee is washed with fresh mountain spring water, creating a clean cup that pairs beautifully with sweet, buttery caramel.',
                'reward_points' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'French Vanilla Bean',
                'price' => 17.00,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Soft, sweet, and comforting. A classic hug in a mug.',
                'image' => '/images/coffee/vanila.jpg',
                'farmer_name' => 'Finca El Puente',
                'country_origin' => 'Costa Rica',
                'altitude' => '1,400m',
                'farm_story' => 'Honey-processed to retain the natural mucilage of the coffee cherry, resulting in a naturally sweet, vanilla-like profile that melts stress away.',
                'reward_points' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Comforting Cinnamon Coffee',
                'price' => 16.50,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Woody and gently spiced kick to warm you up from the inside out.',
                'image' => '/images/coffee/Cinnamon Coffee.jpg',
                'farmer_name' => 'Maria Gonzalez',
                'country_origin' => 'Mexico',
                'altitude' => '1,200m',
                'farm_story' => 'Grown in Chiapas, where the coffee is historically brewed in clay pots with cinnamon sticks (Café de Olla). Maria honors this tradition with her naturally spiced harvest.',
                'reward_points' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rich Mocha',
                'price' => 18.50,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'A decadent mix of dark coffee and velvety chocolate. The ultimate comfort drink.',
                'image' => '/images/coffee/Mocha coffee.jpg',
                'farmer_name' => 'Elkin Guzman',
                'country_origin' => 'Colombia',
                'altitude' => '1,650m',
                'farm_story' => 'Elkin uses an innovative natural fermentation process that brings out massive chocolate notes in the bean, requiring almost no added syrup for its rich flavor.',
                'reward_points' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cozy Pumpkin Spice',
                'price' => 19.00,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'A seasonal blend of cinnamon, nutmeg, and clove for the perfect cozy afternoon.',
                'image' => '/images/coffee/Pumpkin Spice.jpg',
                'farmer_name' => 'Various Smallholders',
                'country_origin' => 'Sumatra',
                'altitude' => '1,500m',
                'farm_story' => 'Sourced from Sumatra where the wet-hulling process gives the coffee a heavy, syrupy body that holds up perfectly to warm autumn spices.',
                'reward_points' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sweet Toffee Coffee',
                'price' => 17.50,
                'mood_id' => $relaxingMood->id,
                'category_id' => $coffeeCat->id,
                'is_deal' => false,
                'description' => 'Deep brown-sugar and butter notes. A sweet treat to reward yourself.',
                'image' => '/images/coffee/Toffee Coffee.jpg',
                'farmer_name' => 'Diego Bermudez',
                'country_origin' => 'Colombia',
                'altitude' => '1,900m',
                'farm_story' => 'Using a thermal shock processing method, Diego locks the sugars into the bean early, creating a distinct, unforgettable toffee sweetness.',
                'reward_points' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === BAKERY ITEMS (With Expert Pairings) ===
            [
                'name' => 'Fudgy Dark Chocolate Brownie',
                'price' => 6.00,
                'mood_id' => $focusMood->id,
                'category_id' => $brownieCat->id,
                'is_deal' => false,
                'description' => 'Dense and rich. Pairs perfectly with Pure Espresso or Intense Ristretto to balance the bitterness.',
                'image' => '/images/walnut_fudge_brownie.png', // Fallback to existing artifact
                'farmer_name' => null,
                'country_origin' => null,
                'altitude' => null,
                'farm_story' => null,
                'reward_points' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cinnamon Roll Cake',
                'price' => 7.50,
                'mood_id' => $relaxingMood->id,
                'category_id' => $brownieCat->id,
                'is_deal' => false,
                'description' => 'Warm and iced. Pairs beautifully with Rich Mocha or Warm Caramel Latte.',
                'image' => '/images/espresso_cheesecake_brownie.png',
                'farmer_name' => null,
                'country_origin' => null,
                'altitude' => null,
                'farm_story' => null,
                'reward_points' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Butter Pecan Cookie',
                'price' => 4.50,
                'mood_id' => $focusMood->id,
                'category_id' => $brownieCat->id,
                'is_deal' => false,
                'description' => 'Nutty and sweet. Pairs beautifully with Toasted Hazelnut Blend or Toffee Coffee.',
                'image' => '/images/salted_caramel_brownie.png',
                'farmer_name' => null,
                'country_origin' => null,
                'altitude' => null,
                'farm_story' => null,
                'reward_points' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
